services:
  gateway-service:
    container_name: gateway-service
    image: caddy:2-alpine
    networks:
      - ceo_network
    ports:
      - "8000:80"
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

networks:
  ceo_network:
    external: true

volumes:
  caddy_data:
  caddy_config: